import { useState } from 'react'

function MetadataReviewPage() {
  const [metadata, setMetadata] = useState({
    description: '昭和から令和まで、激動の時代を生き抜いた一人の男の物語。戦後の混乱期に生まれ、高度経済成長とともに成長し、バブル崩壊、震災、そしてコロナ禍を経験した著者が、家族への愛と感謝を込めて綴る自伝的エッセイ。',
    keywords: [
      '自伝', 'エッセイ', '昭和', '令和', '家族', '人生', '日本史'
    ],
    bisac1: 'BIOGRAPHY & AUTOBIOGRAPHY / Personal Memoirs',
    bisac2: 'HISTORY / Asia / Japan',
    backCoverSummary: '「私の人生の物語」は、昭和二十年代に生まれた田中太郎が、戦後の日本とともに歩んだ八十年間を振り返る珠玉のエッセイ集です。少年時代の思い出、仕事への情熱、家族との絆——時代の波に揉まれながらも、決して失わなかった希望の物語。',
  })

  const updateKeyword = (index: number, value: string) => {
    const newKeywords = [...metadata.keywords]
    newKeywords[index] = value
    setMetadata((prev) => ({ ...prev, keywords: newKeywords }))
  }

  const inputStyle = {
    width: '100%', padding: '0.6rem 0.75rem',
    fontSize: '0.9rem', border: '1px solid #e2e8f0',
    borderRadius: 8, outline: 'none',
    boxSizing: 'border-box' as const,
  }

  return (
    <div style={{ minHeight: '100vh', background: '#f1f5f9' }}>
      {/* Top bar */}
      <header style={{
        background: '#1e293b', color: '#fff', padding: '0.75rem 2rem',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <div style={{
            width: 32, height: 32, borderRadius: 6,
            background: '#3b82f6', display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontWeight: 700, fontSize: '0.9rem', color: '#fff',
          }}>K</div>
          <span style={{ fontWeight: 600, fontSize: '1.05rem' }}>KDP Navigator</span>
          <span style={{ color: '#94a3b8', fontSize: '0.85rem', marginLeft: '0.5rem' }}>Metadata Review</span>
        </div>
        <a href="/agent" style={{ fontSize: '0.85rem', color: '#94a3b8', textDecoration: 'none' }}>
          ← Back to Dashboard
        </a>
      </header>

      <div style={{ maxWidth: 900, margin: '0 auto', padding: '1.5rem 2rem' }}>
        {/* Manuscript info */}
        <div style={{
          background: '#fff', borderRadius: 12, padding: '1.25rem',
          boxShadow: '0 1px 3px rgba(0,0,0,0.06)', marginBottom: '1.5rem',
          display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        }}>
          <div>
            <h1 style={{ fontSize: '1.4rem', fontWeight: 700, color: '#1e293b', marginBottom: '0.2rem' }}>
              私の人生の物語
            </h1>
            <div style={{ fontSize: '0.85rem', color: '#64748b' }}>
              by 田中 太郎 — Generated by Claude API
            </div>
          </div>
          <span style={{
            padding: '0.25rem 0.75rem', borderRadius: 20,
            fontSize: '0.8rem', fontWeight: 600,
            color: '#0891b2', background: '#cffafe',
          }}>PDF Ready</span>
        </div>

        <div style={{ display: 'flex', gap: '1.5rem' }}>
          {/* Left column */}
          <div style={{ flex: '1 1 60%', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            {/* Book description */}
            <div style={{
              background: '#fff', borderRadius: 12, padding: '1.5rem',
              boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
            }}>
              <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#1e293b', marginBottom: '0.75rem' }}>
                Book Description
              </h2>
              <textarea
                value={metadata.description}
                onChange={(e) => setMetadata((prev) => ({ ...prev, description: e.target.value }))}
                rows={5}
                style={{ ...inputStyle, resize: 'vertical' }}
              />
              <div style={{ fontSize: '0.8rem', color: '#94a3b8', marginTop: '0.5rem' }}>
                This appears on the Amazon product page. Keep under 4,000 characters.
              </div>
            </div>

            {/* Back cover summary */}
            <div style={{
              background: '#fff', borderRadius: 12, padding: '1.5rem',
              boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
            }}>
              <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#1e293b', marginBottom: '0.75rem' }}>
                Back Cover Summary
              </h2>
              <textarea
                value={metadata.backCoverSummary}
                onChange={(e) => setMetadata((prev) => ({ ...prev, backCoverSummary: e.target.value }))}
                rows={4}
                style={{ ...inputStyle, resize: 'vertical' }}
              />
              <div style={{ fontSize: '0.8rem', color: '#94a3b8', marginTop: '0.5rem' }}>
                Printed on the back cover of the paperback.
              </div>
            </div>
          </div>

          {/* Right column */}
          <div style={{ flex: '1 1 40%', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            {/* Keywords */}
            <div style={{
              background: '#fff', borderRadius: 12, padding: '1.5rem',
              boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
            }}>
              <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#1e293b', marginBottom: '0.75rem' }}>
                Keywords (7)
              </h2>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                {metadata.keywords.map((kw, i) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <span style={{ fontSize: '0.8rem', color: '#94a3b8', width: 20, textAlign: 'right' }}>{i + 1}.</span>
                    <input
                      type="text" value={kw}
                      onChange={(e) => updateKeyword(i, e.target.value)}
                      style={inputStyle}
                    />
                  </div>
                ))}
              </div>
            </div>

            {/* BISAC Categories */}
            <div style={{
              background: '#fff', borderRadius: 12, padding: '1.5rem',
              boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
            }}>
              <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#1e293b', marginBottom: '0.75rem' }}>
                BISAC Categories (2)
              </h2>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                <div>
                  <label style={{ fontSize: '0.8rem', color: '#64748b', fontWeight: 600 }}>Primary</label>
                  <input
                    type="text" value={metadata.bisac1}
                    onChange={(e) => setMetadata((prev) => ({ ...prev, bisac1: e.target.value }))}
                    style={{ ...inputStyle, marginTop: '0.25rem' }}
                  />
                </div>
                <div>
                  <label style={{ fontSize: '0.8rem', color: '#64748b', fontWeight: 600 }}>Secondary</label>
                  <input
                    type="text" value={metadata.bisac2}
                    onChange={(e) => setMetadata((prev) => ({ ...prev, bisac2: e.target.value }))}
                    style={{ ...inputStyle, marginTop: '0.25rem' }}
                  />
                </div>
              </div>
            </div>

            {/* Actions */}
            <div style={{
              background: '#fff', borderRadius: 12, padding: '1.5rem',
              boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
            }}>
              <button style={{
                width: '100%', padding: '0.75rem',
                background: '#1e293b', color: '#fff',
                fontSize: '0.95rem', fontWeight: 600,
                border: 'none', borderRadius: 8, cursor: 'pointer',
                marginBottom: '0.75rem',
              }}>
                Save Changes
              </button>
              <button style={{
                width: '100%', padding: '0.75rem',
                background: '#fff', color: '#7c3aed',
                fontSize: '0.95rem', fontWeight: 600,
                border: '2px solid #7c3aed', borderRadius: 8, cursor: 'pointer',
              }}>
                Regenerate with Claude
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default MetadataReviewPage
